### ISSUE TITLE
No GPU accelerated 2d results

### ISSUE THREAD

**Issue by mworkentine** [nanoporetech/nanonet#26]
I've been able to get nanonet running on a gpu-accelerated node on our local cluster.  1d calling with pyopencl works great and 2d calling without acceleration also works fine.  2d calling with gpu-acceleration seems to run fine, with no errors and even returns the number of reads processed, but gives a divide by zero error. 
```
(nanonet) [matthew.workentine@c1 nanonet_test]$ nanonet2d data calls --jobs 16 --opencl_2d
Processed 5 reads in 12.5708999634s (wall time)
Traceback (most recent call last):
  File "/home/matthew.workentine/miniconda3/envs/nanonet/bin/nanonet2d", line 11, in <module>
    load_entry_point('nanonet==2.0.0', 'console_scripts', 'nanonet2d')()
  File "build/bdist.linux-x86_64/egg/nanonet/nanonetcall_2d.py", line 263, in main
ZeroDivisionError: float division by zero
```
The complement and template fasta files have the correct number of reads but the 2d fasta file is empty, which I assume has to do with the divide by zero error, but I'm not really sure why this file is empty.

**Comment by cjw85** [comment]
Hi @mworkentine,
Apologies that there is only sparse logging, we will endeavour to correct that. If you have the inclination to track down the root cause you may wish to start at:
https://github.com/nanoporetech/nanonet/blob/master/nanonet/nanonetcall_2d.py#L132

Since the 2D calling works (and I presume returns sensible basecalls) I suspect the issue may be one of a OpenCL setup and/or compilation of the OpenCL code/kernel. Can I check that when running `setup.py` you added `opencl2d` to the command line?

**Comment by mworkentine** [comment]
Yeah, I did run `setup.py` with `opencl2d` and everything compiled ok as far as I could tell.  I'll have a look at that line you suggested and see if I can track things down.  Thanks for the info!

**Comment by mworkentine** [comment]
So I've traced the error to:
https://github.com/nanoporetech/nanonet/blob/master/nanonet/caller_2d/caller_2d.py#L305

`viterbi.init_cl` is returning `Kernel ProcessNodes() failed (CL_INVALID_KERNEL_NAME)`

After that I think I'm getting out of my element with the OpenCL code.  Happy to keep debugging as this is likely an issue specific to our system but I may need a few more pointers/things to try.

Thanks!

**Comment by cjw85** [comment]
At first sight, this does appear to be a problem with your OpenCL setup. Can you provide (if possible) details of your hardware and software setup? Which GPU, which OS, which version of OpenCL/OpenCL driver/OpenCL loader, anything else you can provide.

**Comment by mworkentine** [comment]
Hmm, ok.  I'll touch base with our cluster admin and see what they think.  We're running this on CentOS 6.8 with two NVIDIA Tesla K40m GPU accelerators.

Here's the output of `nanonetcall --list_platforms`:
```
============================================================
OpenCL Platforms and Devices
============================================================
Name:     NVIDIA CUDA
Vendor:   NVIDIA Corporation
Version:  OpenCL 1.2 CUDA 7.5.30
    --------------------------------------------------------
    Name:  Tesla K40m
    Type:  GPU
    Max Clock Speed:  745 Mhz
    Compute Units:  15
    Local Memory:  48 KB
    Constant Memory:  64 KB
    Global Memory: 11 GB
    --------------------------------------------------------
    Name:  Tesla K40m
    Type:  GPU
    Max Clock Speed:  745 Mhz
    Compute Units:  15
    Local Memory:  48 KB
    Constant Memory:  64 KB
    Global Memory: 11 GB
```

**Comment by alantsangmb** [comment]
I had the same problem in my Ubuntu with NVIDIA quadro k1200. I had tried to remove opencl and install again but to no avail. Here's the screen output:

>nanonet2d test call --opencl_2d   
Processed 9 reads in 107.679793119s (wall time)
Traceback (most recent call last):
  File "/usr/local/bin/nanonet2d", line 11, in <module>
    load_entry_point('nanonet==2.0.0', 'console_scripts', 'nanonet2d')()
  File "build/bdist.linux-x86_64/egg/nanonet/nanonetcall_2d.py", line 263, in main
ZeroDivisionError: float division by zero

>nanonetcall --list_platforms 

============================================================
OpenCL Platforms and Devices
============================================================
Name:     NVIDIA CUDA
Vendor:   NVIDIA Corporation
Version:  OpenCL 1.2 CUDA 8.0.46
    --------------------------------------------------------
    Name:  Quadro K1200
    Type:  GPU
    Max Clock Speed:  1032 Mhz
    Compute Units:  4
    Local Memory:  48 KB
    Constant Memory:  64 KB
    Global Memory: 4 GB

**Comment by nick297** [comment]
I'm having a similar issue but with no error messages. There are no 2D results using opencl, 1D and gpu works.

~/software/nanonet$ nanonet2d --chemistry r9 --opencl_2d sample_data /tmp/call_opencl_r9
done
attempting 2D
Failed to produce 2D call.
done
attempting 2D
Failed to produce 2D call.
done
attempting 2D
Failed to produce 2D call.
done
attempting 2D
Failed to produce 2D call.
done
attempting 2D
Failed to produce 2D call.
Processed 5 reads in 42.042042017s (wall time)
1D Run network:  10.09 ( 2.475 kb/s,  5.042 kev/s)
1D Decoding:      6.26 ( 3.991 kb/s,  8.130 kev/s)
2D calling:       0.00 ( 0.000 kb/s)
~/software/nanonet$ nanonet2d --chemistry r9  sample_data /tmp/call_r9done
attempting 2D
done
attempting 2D
done
attempting 2D
done
attempting 2D
done
attempting 2D
Processed 5 reads in 131.271103144s (wall time)
1D Run network:  10.46 ( 2.387 kb/s,  4.862 kev/s)
1D Decoding:      6.27 ( 3.984 kb/s,  8.114 kev/s)
2D calling:      91.27 ( 0.284 kb/s)

~/software/nanonet$ nanonetcall --list_platforms

============================================================
OpenCL Platforms and Devices
============================================================
Name:     NVIDIA CUDA
Vendor:   NVIDIA Corporation
Version:  OpenCL 1.2 CUDA 8.0.46
    --------------------------------------------------------
    Name:  GeForce GTX 645
    Type:  GPU
    Max Clock Speed:  823 Mhz
    Compute Units:  3
    Local Memory:  48 KB
    Constant Memory:  64 KB
    Global Memory: 1 GB

**Comment by cjw85** [comment]
I've added some logging around the initialisation of the 2D OpenCL code. Hopefully this will help to track down errors. When testing on multiple platforms most errors we have observed are in the initialisation of the OpenCL device and context.

**Comment by nick297** [comment]
Hi, I've attached logs. Please see below 

nanonet2d --debug --chemistry r9 --opencl_2d sample_data /tmp/call_opencl_r9
[16:28:46 - root] Starting 2D basecalling.
[16:28:46 - caller-2d] Starting 1D calls for read /home/nick/soft/nanonet/sample_data/904896_ch170_read111_strand.fast5.
[16:28:46 - caller-1d] Starting 1D call for template section of /home/nick/soft/nanonet/sample_data/904896_ch170_read111_strand.fast5.
[16:28:52 - caller-1d] Starting 1D call for complement section of /home/nick/soft/nanonet/sample_data/904896_ch170_read111_strand.fast5.
[16:28:57 - caller-2d] Finished 1D calls for read /home/nick/soft/nanonet/sample_data/904896_ch170_read111_strand.fast5.
[16:28:57 - caller-2d] Starting 2D basecall for read /home/nick/soft/nanonet/sample_data/904896_ch170_read111_strand.fast5.
[16:28:58 - nanonet.caller_2d.caller_2d] Attempting to initialise and choose OpenCL device.
[16:28:58 - nanonet.caller_2d.caller_2d] Chosen OpenCL device: GeForce GTX 1050 Ti.
[16:28:58 - nanonet.caller_2d.caller_2d] Could not initialise 2D-basecall OpenCL kernel.
[16:28:58 - nanonet.caller_2d.caller_2d] Failed to perform 2D call: 'NoneType' object is not iterable.
[16:28:58 - caller-2d] Exception from call_2d(): Failed to produce 2D call.
[16:28:58 - caller-2d] Starting 1D calls for read /home/nick/soft/nanonet/sample_data/904896_ch170_read105_strand.fast5.
[16:28:58 - caller-1d] Starting 1D call for template section of /home/nick/soft/nanonet/sample_data/904896_ch170_read105_strand.fast5.
[16:29:04 - caller-1d] Starting 1D call for complement section of /home/nick/soft/nanonet/sample_data/904896_ch170_read105_strand.fast5.
[16:29:09 - caller-2d] Finished 1D calls for read /home/nick/soft/nanonet/sample_data/904896_ch170_read105_strand.fast5.
[16:29:09 - caller-2d] Starting 2D basecall for read /home/nick/soft/nanonet/sample_data/904896_ch170_read105_strand.fast5.
[16:29:09 - nanonet.caller_2d.caller_2d] Attempting to initialise and choose OpenCL device.
[16:29:10 - nanonet.caller_2d.caller_2d] Chosen OpenCL device: GeForce GTX 1050 Ti.
[16:29:10 - nanonet.caller_2d.caller_2d] Could not initialise 2D-basecall OpenCL kernel.
[16:29:10 - nanonet.caller_2d.caller_2d] Failed to perform 2D call: 'NoneType' object is not iterable.
[16:29:10 - caller-2d] Exception from call_2d(): Failed to produce 2D call.
[16:29:10 - caller-2d] Starting 1D calls for read /home/nick/soft/nanonet/sample_data/904896_ch170_read104_strand.fast5.
[16:29:10 - caller-1d] Starting 1D call for template section of /home/nick/soft/nanonet/sample_data/904896_ch170_read104_strand.fast5.
[16:29:11 - caller-1d] Starting 1D call for complement section of /home/nick/soft/nanonet/sample_data/904896_ch170_read104_strand.fast5.
[16:29:12 - caller-2d] Finished 1D calls for read /home/nick/soft/nanonet/sample_data/904896_ch170_read104_strand.fast5.
[16:29:12 - caller-2d] Starting 2D basecall for read /home/nick/soft/nanonet/sample_data/904896_ch170_read104_strand.fast5.
[16:29:12 - nanonet.caller_2d.caller_2d] Attempting to initialise and choose OpenCL device.
[16:29:12 - nanonet.caller_2d.caller_2d] Chosen OpenCL device: GeForce GTX 1050 Ti.
[16:29:12 - nanonet.caller_2d.caller_2d] Could not initialise 2D-basecall OpenCL kernel.
[16:29:12 - nanonet.caller_2d.caller_2d] Failed to perform 2D call: 'NoneType' object is not iterable.
[16:29:12 - caller-2d] Exception from call_2d(): Failed to produce 2D call.
[16:29:12 - caller-2d] Starting 1D calls for read /home/nick/soft/nanonet/sample_data/904896_ch170_read108_strand.fast5.
[16:29:12 - caller-1d] Starting 1D call for template section of /home/nick/soft/nanonet/sample_data/904896_ch170_read108_strand.fast5.
[16:29:14 - caller-1d] Starting 1D call for complement section of /home/nick/soft/nanonet/sample_data/904896_ch170_read108_strand.fast5.
[16:29:16 - caller-2d] Finished 1D calls for read /home/nick/soft/nanonet/sample_data/904896_ch170_read108_strand.fast5.
[16:29:16 - caller-2d] Starting 2D basecall for read /home/nick/soft/nanonet/sample_data/904896_ch170_read108_strand.fast5.
[16:29:17 - nanonet.caller_2d.caller_2d] Attempting to initialise and choose OpenCL device.
[16:29:17 - nanonet.caller_2d.caller_2d] Chosen OpenCL device: GeForce GTX 1050 Ti.
[16:29:17 - nanonet.caller_2d.caller_2d] Could not initialise 2D-basecall OpenCL kernel.
[16:29:17 - nanonet.caller_2d.caller_2d] Failed to perform 2D call: 'NoneType' object is not iterable.
[16:29:17 - caller-2d] Exception from call_2d(): Failed to produce 2D call.
[16:29:17 - caller-2d] Starting 1D calls for read /home/nick/soft/nanonet/sample_data/904896_ch170_read114_strand.fast5.
[16:29:17 - caller-1d] Starting 1D call for template section of /home/nick/soft/nanonet/sample_data/904896_ch170_read114_strand.fast5.
[16:29:22 - caller-1d] Starting 1D call for complement section of /home/nick/soft/nanonet/sample_data/904896_ch170_read114_strand.fast5.
[16:29:27 - caller-2d] Finished 1D calls for read /home/nick/soft/nanonet/sample_data/904896_ch170_read114_strand.fast5.
[16:29:27 - caller-2d] Starting 2D basecall for read /home/nick/soft/nanonet/sample_data/904896_ch170_read114_strand.fast5.
[16:29:28 - nanonet.caller_2d.caller_2d] Attempting to initialise and choose OpenCL device.
[16:29:28 - nanonet.caller_2d.caller_2d] Chosen OpenCL device: GeForce GTX 1050 Ti.
[16:29:28 - nanonet.caller_2d.caller_2d] Could not initialise 2D-basecall OpenCL kernel.
[16:29:28 - nanonet.caller_2d.caller_2d] Failed to perform 2D call: 'NoneType' object is not iterable.
[16:29:28 - caller-2d] Exception from call_2d(): Failed to produce 2D call.
Processed 5 reads in 41.6126070023s (wall time)
1D Run network:   9.93 ( 2.514 kb/s,  5.120 kev/s)
1D Decoding:      6.06 ( 4.121 kb/s,  8.395 kev/s)
2D calling:       0.00 ( 0.000 kb/s)
