### ISSUE TITLE
missing 

### ISSUE THREAD

**Issue by mhowison** [nanoporetech/nanonet#28]
I installed nanonet at commit #e8bb655, but when I try to run simulate_minion I get the error below. It looks like the `simulate` package may not have been committed? I don't see any source code for it in the repo.

$ simulate_minion -h
Traceback (most recent call last):
  File "/gpfs/runtime/opt/nanonet/20161004/bin/simulate_minion", line 9, in <module>
    load_entry_point('nanonet==2.0.0', 'console_scripts', 'simulate_minion')()
  File "/gpfs/runtime/opt/nanonet/20161004/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 549, in load_entry_point
  File "/gpfs/runtime/opt/nanonet/20161004/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2542, in load_entry_point
  File "/gpfs/runtime/opt/nanonet/20161004/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2202, in load
  File "/gpfs/runtime/opt/nanonet/20161004/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2208, in resolve
ImportError: No module named simulate.simulate_minion

**Comment by mhowison** [comment]
@cjw85 checking in on this again, and looking at setup.py again I think there is a missing file `nanonet/simulate/simulate_minion.py`? Maybe an easy fix to commit and push that file? We would love to start using this simulator!

**Comment by Steven-N-Hart** [comment]
Ditto

**Comment by mhowison** [comment]
I am also still very interested in testing out the simulator. In the meantime, I looked at nanosim (https://github.com/bcgsc/NanoSim) but unfortunately it can only simulate base-called FASTA data. We have a sequencing project that we are considering using MinION for, but we need to be able to evaluate and model the potential use of the raw squiggle data with simulations before we invest in sequencing.

**Comment by mattloose** [comment]
With respect to this, I wouldn't go with modeled raw squiggle data - I would just grab real data from somewhere and use that - there are a lot of datasets available now with raw data included. In my experience, simulations of raw data to date do not accurately model real raw data.

**Comment by cjw85** [comment]
Apologies @mhowison for the lack of reply here.

As @mattloose points out, there are now various datasets available publically which are probably more suited to your purpose, simulated data will be misleading in this application. For the time being we have removed the remaining code stubs.

**Comment by mhowison** [comment]
Hi @mattloose and @cjw85 - thanks for your responses! Our hope was to generate simulated data for known plasmid HIV sequences for which we already collected Illumina MiSeq data - so that we could experiment with combining Illumina and MinION data, or even using the MinION data exclusively. I tried a quick Google search and didn't find any results for publicly available MinION data for HIV, but maybe you know of a dataset or a better place for me to search?

Out of curiosity, @mattloose what were some of the inaccuracies you ran into with MinION simulations?

**Comment by mattloose** [comment]
Hi Mark,

I don't know of any HIV data out there, but there are datasets available now with Illumina data available as well - you could look at ebola or zika datasets as an example?

The issue I have had with MinION simulations is that they miss subtleties in the data that might be important - particularly at read starts and ends. It's also hard to simulate behaviours that aren't known yet! 

So I'd argue that it would be better to run your tests on available data and then just take the plunge and generate some data yourself!

Cheers

Matt
