### ISSUE TITLE
nanonet2d error Mac OS X

### ISSUE THREAD

**Issue by nickloman** [nanoporetech/nanonet#36]
Any ideas? nanonetcall from the same build works.

$ nanonet2d pass
Traceback (most recent call last):
  File "/usr/local/bin/nanonet2d", line 9, in <module>
    load_entry_point('nanonet==2.0.0', 'console_scripts', 'nanonet2d')()
  File "build/bdist.macosx-10.11-x86_64/egg/nanonet/nanonetcall_2d.py", line 240, in main
  File "build/bdist.macosx-10.11-x86_64/egg/nanonet/nanonet/util.py", line 455, in tang_imap
  File "build/bdist.macosx-10.11-x86_64/egg/nanonet/nanonet/fast5.py", line 952, in iterate_fast5
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by cjw85** [comment]
Hi @nickloman,
The nanonet2d program requires a second option: the prefix for the output sequence files. See https://github.com/nanoporetech/nanonet#2d-basecalling
