### ISSUE TITLE
nanonettrain

### ISSUE THREAD

**Issue by rojinsafavi** [nanoporetech/nanonet#41]
Hello again,

Thank you very much for your quick responses to my questions.
I would like to use nanonettrain to see how the training work. Is there any test data available to do that? Something that will be compatible with the file you mentioned in the README : 
nanonet/data/default_model.tmpl
I have used my own fast5 files for this purpose, but I'm getting an error:

$ nanonettrain --train ~/training-set/ --val ~/validation-set/ --output fasta --model ~/nanonet/nanonet/data/default_model.tmpl
Creating training data NetCDF: /tmp/nn_data_SJQJBU_train.netcdf
Creating training data NetCDF: /tmp/nn_data_SJQJBU_validation.netcdf
Traceback (most recent call last):
  File "/soe/rojinsafavi/anaconda2/bin/nanonettrain", line 11, in <module>
    load_entry_point('nanonet==2.0.0', 'console_scripts', 'nanonettrain')()
  File "build/bdist.linux-x86_64/egg/nanonet/nanonettrain.py", line 123, in main
  File "build/bdist.linux-x86_64/egg/nanonet/util.py", line 463, in tang_imap
  File "/soe/rojinsafavi/anaconda2/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
Exception: Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/nanonet/util.py", line 402, in except_functor
    return function(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/nanonet/nanonettrain.py", line 84, in prepare_input_file
    **kwargs
  File "build/bdist.linux-x86_64/egg/nanonet/features.py", line 182, in make_currennt_training_input_multi
    X = events_to_features(get_events(fast5_files[0], **callback_kwargs), window=window)
  File "build/bdist.linux-x86_64/egg/nanonet/features.py", line 127, in get_events_ont_mapping
    events, _ = fh.get_any_mapping_data(section=section)
  File "build/bdist.linux-x86_64/egg/nanonet/fast5.py", line 852, in get_any_mapping_data
    .format(self.filename)
ValueError: Cannot find any mapping data at paths I know about in /soe/rojinsafavi/training-set/DEAMERNANOPORE_20160805_FNFAD19383_MN16450_sequencing_run_MA_821_R9_gEcoli_MG1655_08_05_16_89825_ch121_read15199_strand.fast5. Consider using get_mapping_data() with analysis argument.

Regards

**Comment by cjw85** [comment]
As per the README, nanonet does not contain code to prepare training data. Several other users have done this. You may wish to start by reading through this thread https://github.com/nanoporetech/nanonet/issues/32 and talking to @scottgigante.

**Comment by rojinsafavi** [comment]
Thanks!

What options should I use to use this function : get_mapping_data() ?

Thanks!

**Comment by cjw85** [comment]
@rojinsafavi 
The functions `get_events_ont_mapping` and `get_labels_ont_mapping` are specialized to a variant of .fast5 file that ONT use internally and contain extra datasets beyond those found in .fast5 files produced by MinKnow or ONT standalone basecallers.

The calling of these functions in `make_currennt_training_input_multi` needs to be replaced with alternatives to read the training input from alternative sources.

**Comment by rojinsafavi** [comment]
Hello,
I managed to get the proper input format. I was able to run nanonettrain on my Mac, but when I run it on our sever I get the following error:

$ nanonettrain --train sample_data/train/ --val sample_data/val/ --output fasta --model sample_data/template.json --kmer_length 5 --section template 
Creating training data NetCDF: /tmp/nn_data_ERTYHB_train.netcdf
Creating training data NetCDF: /tmp/nn_data_ERTYHB_validation.netcdf
Adding: g.fast5
Adding: t.fast5
Adding: z.fast5
Adding: y.fast5
Adding: x.fast5

Running currennt with: /tmp/nn_ERTYHB.cfg
Traceback (most recent call last):
  File "/soe/rojinsafavi/anaconda2/bin/nanonettrain", line 11, in <module>
    load_entry_point('nanonet==2.0.0', 'console_scripts', 'nanonettrain')()
  File "build/bdist.linux-x86_64/egg/nanonet/nanonettrain.py", line 184, in main
  File "build/bdist.linux-x86_64/egg/nanonet/__init__.py", line 59, in run_currennt_noisy
  File "/soe/rojinsafavi/anaconda2/lib/python2.7/subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/soe/rojinsafavi/anaconda2/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/soe/rojinsafavi/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/soe/rojinsafavi/anaconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

I have currennt net installed on the server, and I check the installation by running the test file given at worked.

Kind regards,
Rojin

**Comment by rojinsafavi** [comment]
I managed to get the correct labeling for my data. nanonettrain seems to work fine on my Mac, but when I run in on the server I et the following error:


Running currennt with: /tmp/nn_PRYGWB.cfg
Traceback (most recent call last):
  File "/soe/rojinsafavi/anaconda2/bin/nanonettrain", line 11, in <module>
    load_entry_point('nanonet==2.0.0', 'console_scripts', 'nanonettrain')()
  File "build/bdist.linux-x86_64/egg/nanonet/nanonettrain.py", line 184, in main
  File "build/bdist.linux-x86_64/egg/nanonet/__init__.py", line 59, in run_currennt_noisy
  File "/soe/rojinsafavi/anaconda2/lib/python2.7/subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/soe/rojinsafavi/anaconda2/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/soe/rojinsafavi/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/soe/rojinsafavi/anaconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

I was wondering if you know why I'm getting this error? 

Thanks,
Rojin

**Comment by cjw85** [comment]
Hi @rojinsafavi,

The above error looks to be caused by nanonet not being able to invoke currennt. On your server are you able to run currennt directly (outside of nanonet)? If so you should set the environment variable "CURRENNT" to point at your currennt executable.

**Comment by rojinsafavi** [comment]
When I go to the test folder within the currennt and run the "run.py" it works fine.

I added following path to my environment: /soe/rojinsafavi/currennt/build , /soe/rojinsafavi/currennt/build/currennt

But I'm still getting the permission error when I run nanonettrain.

I noticed that when I run currennt alone on the server I get : 

$ currennt
currennt: Command not found

$  which currennt
currennt: Command not found.

$ echo $PATH
/soe/rojinsafavi/currennt/build/currennt/
/soe/rojinsafavi/currennt/build/

But when I do it on my mac it seems to working fine.

Thanks for helping!

**Comment by cjw85** [comment]
nanonettrain requires currennt to be on your PATH or the full path to currennt be specified by the CURRENNT environment variable (see https://github.com/nanoporetech/nanonet/blob/master/nanonet/__init__.py#L14).

It looks to me like you should try:
$ PATH=/soe/rojinsafavi/currennt/build/currennt/:$PATH

providing that the currennt executable has bee correctly compiled for you system and resides in /soe/rojinsafavi/currennt/build/currennt/

**Comment by rojinsafavi** [comment]
It's working now, thanks for the tips
