### ISSUE TITLE
OSX install problem / user accessibility

### ISSUE THREAD

**Issue by rec3141** [nanoporetech/nanonet#50]
I have an admin account to install things and a user account to use them, but I cannot use nanonet as a user when it is installed by admin --  I get the following error. The installation directory (using --prefix) is publicly accessible and the program is executable. Any ideas how to fix it? Thanks.

Traceback (most recent call last):
  File "/work/cryomics/apps/nanonet/bin/nanonetcall", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 959, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'nanonet==2.0.0' distribution was not found and is required by the application

**Comment by rec3141** [comment]
fyi if I try to do `python setup.py install` using my user account I get the error that was reported previously about absolute paths. It works on the admin account (for which homebrew is used).



```
*********************************************************************************
Proprietary and confidential information of Oxford Nanopore Technologies, Limited
All rights reserved; (c)2016: Oxford Nanopore Technologies, Limited
*********************************************************************************

System is Darwin
By default the 2D basecaller (standard and OpenCL) are not built.
To enable these use 'with2d' and 'opencl2d' command line options.

Adding OSX compile/link options
running install
running bdist_egg
running egg_info
writing requirements to nanonet.egg-info/requires.txt
writing nanonet.egg-info/PKG-INFO
writing top-level names to nanonet.egg-info/top_level.txt
writing dependency_links to nanonet.egg-info/dependency_links.txt
writing entry points to nanonet.egg-info/entry_points.txt
reading manifest file 'nanonet.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs'
writing manifest file 'nanonet.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.12-intel/egg
running install_lib
running build_py
error: Error: setup script specifies an absolute path:

    /Volumes/work/cryomics/apps/nanonet-2.0.0/nanonet/decoding.cpp

setup() arguments must *always* be /-separated paths relative to the
setup.py directory, *never* absolute paths.
```

**Comment by rec3141** [comment]
pps I tried installing as admin with `sudo python setup.py install` to the default directory and get this error when trying to run the program. A solution to any of these problems would work.

```
Traceback (most recent call last):
  File "/usr/local/bin/nanonetcall", line 9, in <module>
    load_entry_point('nanonet==2.0.0', 'console_scripts', 'nanonetcall')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.macosx-10.12-intel/egg/nanonet/nanonetcall.py", line 17, in <module>
  File "build/bdist.macosx-10.12-intel/egg/nanonet/decoding.py", line 12, in <module>
  File "build/bdist.macosx-10.12-intel/egg/nanonet/util.py", line 36, in get_shared_lib
UnboundLocalError: local variable 'lib_file' referenced before assignment
```

when I delete the installation `build` directory as suggested in another issue, I then get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/nanonetcall", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 649, in _build_master
    ws = cls()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 642, in __init__
    self.add_entry(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 698, in add_entry
    for dist in find_distributions(entry, True):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2115, in find_on_path
    path_item = _normalize_cached(path_item)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2283, in _normalize_cached
    _cache[filename] = result = normalize_path(filename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2277, in normalize_path
    return os.path.normcase(os.path.realpath(filename))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 376, in realpath
    return abspath(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 364, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory
```

**Comment by cjw85** [comment]
Hi @rec3141 

Have you resolved this issue? The issue concerning absolute paths should be resolved in the latest version.

Is there a particular reason you use an admin account to install things? I do personally find that this complicates python packaging on OSX.
